server:
  port: 8081

spring:
  application:
    name: passenger-api
    application:
      name: passenger-api
    redis:
      host: localhost
      port: 6379
      database: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true



